language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy3.5"

# Enable 3.7 without globally enabling sudo and dist: xenial for other build jobs
# source: https://github.com/travis-ci/travis-ci/issues/9815
matrix:
  include:
    - python: "3.7"
      dist: xenial
      sudo: true

install:
  - pip install pytest-cov msgpack-python python-coveralls pytest-pep8
  - pip install -e .
  
script:
  - py.test --pep8 src/ahocorapy/ --cov src/ahocorapy/ --cov-report term-missing  tests/ahocorapy_test.py

after_success:
  - coveralls